[application]
name = "leaflet-webgl-hybrid-poc"
out_dir = "dist"
asset_dir = "public"
default_platform = "web"

[web.app]
# SPAルーティング用（404時にindex.htmlを返す）
index_on_404 = true
# GitHub Pages用のbase path
base_path = "leaflet-webgl-hybrid-poc"


[web.watcher]
reload_html = true
watch_path = ["src", "public"]

[[web.pre_build]]
command = "npm"
command_arguments = ["run", "build-css"]

[[web.pre_build]]
command = "cp"
command_arguments = ["src/tailwind-generated.css", "public/"]

[bundle]
# リリースビルド時の設定
[bundle.web]
[bundle.web.release]