[application]
name = "leaflet-webgl-hybrid-poc"
out_dir = "dist"
asset_dir = "public"
default_platform = "web"

[web.app]
# GitHub Pagesのリポジトリ名に合わせる（開発時もこのパスを使用）
base_path = "leaflet-webgl-hybrid-poc"
# SPAルーティング用（404時にindex.htmlを返す）
index_on_404 = true

[web.resource]
# 外部スクリプトとスタイルを追加
script = [
    "https://unpkg.com/leaflet@1.9.4/dist/leaflet.js",
    "https://cdnjs.cloudflare.com/ajax/libs/pixi.js/7.2.4/pixi.min.js"
]
style = [
    "https://unpkg.com/leaflet@1.9.4/dist/leaflet.css",
    "./assets/style.css",
    "./assets/tailwind-generated.css"
]

[web.watcher]
reload_html = true
watch_path = ["src", "public"]

[[web.pre_build]]
command = "npm"
command_arguments = ["run", "build-css"]

[[web.pre_build]]
command = "cp"
command_arguments = ["src/tailwind-generated.css", "public/"]

[bundle]
# リリースビルド時の設定
[bundle.web]
[bundle.web.release]