[application]
name = "leaflet-webgl-hybrid-poc"
out_dir = "dist"
asset_dir = "public"
default_platform = "web"

[web.app]
# SPAルーティング用（404時にindex.htmlを返す）
index_on_404 = true
# base_pathは開発環境では設定しない（"/"になる）


[web.watcher]
reload_html = true
watch_path = ["src", "public", "assets"]

[[web.pre_build]]
command = "npm"
command_arguments = ["run", "build-css"]

[[web.pre_build]]
command = "cp"
command_arguments = ["assets/tailwind.css", "public/"]

[bundle]
# リリースビルド時の設定
[bundle.web]
[bundle.web.release]