# Trunk configuration
[build]
dist = "dist"
public_url = "/"

[[hook]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "scripts/post-build-optimize.sh"]

[watch]
ignore = ["target", "dist"]

[serve]
port = 8080
open = false

# Skip wasm-opt in Trunk (we'll do it manually)
# [tools]
# wasm_opt = false

[[hook]]
stage = "pre_build"
command = "npm"
command_arguments = ["run", "build-css"]

# Clean URLs for better UX
# [clean_urls]
# enabled = true