name: Deploy Demo to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      
      - name: Install Dioxus CLI
        uses: taiki-e/install-action@v2
        with:
          tool: dioxus-cli@0.6.4-alpha
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install npm dependencies
        run: npm install
      
      - name: Install Tailwind CSS
        run: |
          # Download Tailwind CSS standalone CLI v4
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
          chmod +x tailwindcss-linux-x64
          mv tailwindcss-linux-x64 tailwindcss
      
      - name: Bundle optimized WASM
        run: |
          # Use dx bundle instead of dx build for static sites
          # This outputs directly to dist/ with proper paths
          dx bundle --platform web --release --public-url leaflet-webgl-hybrid-poc
      
      - name: Prepare for GitHub Pages
        run: |
          # Create symlink for SPA routing (GitHub Pages converts to actual copy)
          ln -s index.html dist/404.html
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4